# _apps_rel_2020.yml
# _apps_rel_2024.yml
# _apps_sim.yml
# _apps_his.yml
# script/R/complexregression.R
# script/R/testing.R
# inst/shinyapps/r2rsim/app.R
# inst/shinyapps/manimp/app.R
# inst/shinyapps/empapp/app.R
# inst/shinyapps/restor/app.R
# script/python/polysolver.py
# script/python/abc.py
# script/R/stylized.R
# R/wasmconverting.R
# R/wasmnonverting.R
# data-raw/record_dynamic.R
# https://lotariohw26.github.io/MD_WASMS/r/examples/
# https://lotariohw26.github.io/MD_WASMS/py/examples/
# data-raw/metadata.json
# https://docs.google.com/document/d/1TEt-ZqPkX0jcpFLoE6PAbCZh0s8kxFzcsKC_3f0dShk/edit
# MD_WASMS/examples/r/MD-script/testing.R
# MD_WASMS/examples/r/MD-script/testing.R
# if(Sys.info()[['sysname']]=="Emscripten") { 1 } else { 2 }
project:
  type: website
  output-dir: docs
  #  pre-render: prerendr.R
  render:
    - "index.qmd"
    # - "presentation.qmd"
    # - "paper.qmd"
    #    - "tab.qmd"
    #- "tabset.qmd"
    #- "metaview.qmd"
    #- "laws.qmd"
    #- "man_bib.qmd"
    ##    - "simulations.qmd"
    ##    - "rigging.qmd"
    #- "analyzer.qmd"
    #    - "restoration.qmd"
    # - "randpython.qmd"
    #    - "calculator.qmd"
website:
  title: "{{< var titls >}}"
  navbar:
    left:
      - text: "Index"
        href: index.qmd
        #- text: "Documentation"
        #  menu:
        #  - text: "Presentation" 
        #    href: "presentation.qmd"
        #  #        #        - text: "Addendum 1: Arizona"
        #        #          href: "addendum/Addendum_az.qmd"
        #        #        - text: "Addendum 2: Nevada"
        #        #          href: "addendum/Addendum_ne.qmd"
        #        #        - text: "Paper"
        #        #          href: paper.qmd
        #- text: "Tabset"
        #  href: tabset.qmd
        # - text: "Shiny applications"
        #  href: https://lotariohw26.github.io/MD_WASMS/py/examples/
        #  - text: "R2 simulator"
        #  - text: "Rigging of a natural election"
        #  - text: "Election results analyzer"
        #  - text: "Restoration of a rigged election"
        #      - text: E-books
        #        menu:
        #        - text: "Analysis of the 2020 and 2022 General Elections of Clark and Washoe Counties, Nevada"
        #          href: "https://lotariohw26.github.io/MD_BOOK1"
        #      - text: Bibliography
        #        href: man_bib.qmd
        #- text: Appendix
        #  menu:
        #  - text: "20 laws and 40 isometries"
        #    href: "laws.qmd"
        #- text: WebAssembly
        #  menu:
        #  - text: "Analyzer"
        #    href: "analyzer.qmd"
        #- text: "Simulations"
        #  href: "simulations.qmd"
        #- text: "Rigging"
        #  href: "rigging.qmd"
        #- text: "Restoration"
        #  href: "restoration.qmd"
        #- text: "Pyodide"
        #  href: "randpython.qmd"
        # href: "randpython.qmd"
      - text: "Pyodide"
  repo-url: "https://github.com/lotariohw26/ManifoldDestiny"
  site-url: "https://lotariohw26.github.io/ManifoldDestiny/"
  reader-mode: false
  repo-actions: [edit]
  page-footer: 
     left: "" 
     right: 
       - icon: github
         href: https://github.com/lotariohw26/ManifoldDestiny
format:
  html:
    toc: true
    toc-depth: 3
    Mainfont: "Arial"
    Font size: 1.2
    Line stretch: 1.5

bibliography: man_bib.bib
execute:
  echo: false
# https://lotariohw26.github.io/ManifoldDestiny/
# https://lotariohw26.github.io/MD_WASMS/py/examples/
# #1 Data transformation
# #2 Standardization 
# #3 Counting
