---
title: "{{< var titll >}}"
abstract: "Abstract goes here"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

```{r}
knitr::knit_exit()
```


```{r, echo=F}
ManifoldDestiny::wasmconload()
#source(paste0(rprojroot::find_rstudio_root_file(),'/script/R/simulations.R'))
```

```{r}
#| echo: false
#| output: false
apps <- appn1
```
{{< include tabpar.qmd >}}



# {{< var sec1.nmn >}}
## {{< var sec1.un1 >}}
## {{< var sec1.un2 >}}
## {{< var sec1.un3 >}}
## {{< var sec1.un4 >}}
## {{< var sec1.un5 >}}
## {{< var sec1.un6 >}}
## {{< var sec1.un7 >}}

# {{< var sec2.nmn >}}
## {{< var sec2.un1 >}}
## {{< var sec2.un2 >}}
## {{< var sec2.un3 >}}
## {{< var sec2.un4 >}}
## {{< var sec2.un5 >}}

# {{< var sec3.nmn >}}




## {{< var sec3.un1 >}}
```{r}
#| echo: false
#| output: false
apps <- appsn
```
{{< include tabpar.qmd >}}


```{r}
knitr::knit_exit()
```

## {{< var sec3.un2 >}}
### Normal form
```{r}
#| echo: false
#| output: false
apps <- apprn
```
{{< include tab.qmd >}}

---

### Hybrid
```{r}
#| echo: false
#| output: false
apps <- apprh
```
{{< include tab.qmd >}}

---

### Opposition
```{r}
#| echo: false
#| output: false
apps <- appro
```

{{< include tab.qmd >}}

# {{< var sec5.nmn >}}

# {{< var sec6.nmn >}}

## {{< var sec6.un1 >}}
```{r}
#| echo: false
#| output: false
apps <- app1
```
{{< include tabpar.qmd >}}

## {{< var sec6.un2 >}}
```{r}
#| echo: false
#| output: false
apps <- app2
```
{{< include tabpar.qmd >}}


## {{< var sec6.un3 >}}
```{r}
#| echo: false
#| output: false
apps <- app2
```
{{< include tabpar.qmd >}}
## {{< var sec6.un4 >}}
```{r}
#| echo: false
#| output: false
apps <- app4
```
{{< include tabpar.qmd >}}


# {{< var sec7.nmn >}}
## {{< var sec7.un1 >}}

# {{< var sec8.nmn >}}




```{r}
knitr::knit_exit()
```
