```{r}
#| echo: false
#| output: false
#| message: false
#| warning: false
ManifoldDestiny::wasmconload()
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmconverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmnonverting.R"))
apps <- apsnn
adat <- apps[[1]]
amet <- apps[[2]]
cogr <- Countinggraphs(apps[[1]])
selo <- seloutput(selreport(apps))
#options(digits = 2)                                                                                               
```


::: {.panel-tabset}
### {{< var tabs.h0 >}} 
```{r, echo=F}
kableExtra::kbl(selo[['decs']]) %>% kableExtra::kable_paper(full_width = F) %>% kableExtra::kable_styling(font_size=8)
```
### {{< var tabs.h1 >}} 
```{r, echo=F}
paste0(amet$mtd$nmn,amet$mtd$yea,amet$mtd$std,amet$mtd$cou)
```
### {{< var tabs.h2 >}}
```{r, echo=F, out.width="60%"}
selo[['corxy']]
```
### {{< var tabs.h3 >}}
```{r, echo=F, out.width="60%"}
selo[['qunt']]
```
### {{< var tabs.h4 >}}
```{r, echo=F}
selo[['ro3d']]
```
### {{< var tabs.h5 >}}
```{r, echo=F, out.width="60%"}
selo[['regr']]
selo[['regi']]
```
### {{< var tabs.h6 >}}
```{r, echo=F, out.width="60%"}
kableExtra::kbl(selo[['cmp']]) %>% kableExtra::kable_paper(full_width = F) %>% kableExtra::kable_styling(font_size=8)
```
### {{< var tabs.h7 >}}
```{r, echo=F, out.width="60%"}
selo[['resp']]
```
### {{< var tabs.h8 >}}
```{r, echo=F, out.width="60%"}
selo[['bs']]
```
::: 





