---
title: ""
---

```{r}
#| echo: false
#| output: false
#| message: false
ManifoldDestiny::wasmconload()
library(ManifoldDestiny)
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmconverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmnonverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),'/script/R/simulations.R'))
```

::: {.callout-caution collapse="true"}
## {{< var tabh.h0 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- basc
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::


::: {.callout-caution collapse="true"}
## {{< var tabh.h1 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- rigv[[1]]
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var tabh.h2 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- rigv[[2]]
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var tabh.h3 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- rigv[[3]]
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var sec6.un1 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- app1
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var sec6.un2 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- app2
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var sec6.un3 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- app3
app_a_out <- basc
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::

::: {.callout-caution collapse="true"}
## {{< var sec6.un4 >}}
```{r, echo=FALSE, results='asis',warning=F}
apps <- app4
app1_fil <- paste0(rprojroot::find_rstudio_root_file(), '/tab.qmd')
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[50:length(text)], collapse = "\n"), quiet = TRUE))
```
:::


