library(ManifoldDestiny)
library(ggplot2)
library(dplyr)
library(ManifoldDestiny)
library(htmltools)
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmconverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmnonverting.R"))
#######################################################################################################################################################
set.seed(1)
#######################################################################################################################################################
P  <- c(1,2,3,4,5,6)
S  <- c(60,60,60,60,60,60)
T  <- c(40,40,40,40,40,40)
U  <- c(40,40*2,40*3,40*4,40*5,40*6)
V  <- c(60,60*2,60*3,40*4,40*5,40*6)
Up <- c(40,40*2-5,40*3-15,40*4,40*5,40*6)
Vp <- c(60,60*2+5,60*3+15,40*4,40*5,40*6)
R  <- c(200,200*2,200*3,200*4,200*5,200*6)
pro_rec_ex1 <- data.frame(P=c(1,2,3),S=S,T=T,U=U,V=V,R=R) 
pro_rec_ex2 <- data.frame(P=c(1,2,3),S=S,T=T,U=Up,V=Vp,R=R) 
pro_elc_ex1 <- Countinggraphs(pro_rec_ex1,polyn=1)
pro_elc_ex2 <- Countinggraphs(pro_rec_ex2,polyn=1)
#########################################################################################################################################################
app0_rp <- selreport(app0)
app_0_out <- seloutput(app0_rp)
app1_rp <- selreport(app1)
app_1_out <- seloutput(app1_rp)
app2_rp <- selreport(app2)
app_2_out <- seloutput(app2_rp)
app3_rp <- selreport(app2)
app_3_out <- seloutput(app3_rp)
app4_rp <- selreport(app4)
app_4_out <- seloutput(app4_rp)
app7_rp <- selreport(yout)
app_7_out <- seloutput(app7_rp)
###########################################################################################################################################################

