---
title: " "
output: html_document
---



```{r eval=F, echo=F}
setwd(rprojroot::find_rstudio_root_file())
filp <- 'vignettes/Graphical.Rmd'
rmarkdown::render(filp)
system(paste0('brave vignettes/Graphical.html'))
```

```{r include=FALSE}
library(ManifoldDestiny)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(randNames)
library(openxlsx)
library(patchwork)
library(writexl)
library(plotly)
library(ViewPipeSteps)
library(RefManageR)
library(ggpubr)
```

```{r, eval=T, echo=F, message=F, warning=F}
### Loading equations
#setwd(rprojroot::find_rstudio_root_file())
source('../inst/script/stylized.R')
```

```{r include=FALSE}
library(ManifoldDestiny)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(randNames)
library(openxlsx)
library(patchwork)
library(writexl)
library(plotly)
library(ViewPipeSteps)
library(RefManageR)
library(ggpubr)
```

# Graphical: Fair election process abc
## Tab 1
Some text here 

```{r, echo=F, message=F, warning=F}
g <- gcou$plotxy(c("x","y"))
ggplotly(g)
```

## Tab 2
```{r, echo=F, message=F, warning=F}
#gquil <- gcou$plot2d(selvp=c("x","y","alpha"),selvl=c("x_pred","y_pred","alpha_pred"))
#gzeta <- gcou$plot2d(selvp=c("zeta"),selvl='zeta_m')
#plotly::subplot(gquil,gzeta,nrows=2)
```

## Tab 3	
```{r, echo=F, message=F, warning=F}
#plotly(gcou$resplot(resvar=c('zeta_m','y_s_res')))
```

## Tab 4	
```{r, echo=F, message=F, warning=F}
#gcou$resplot(resvar=c('zeta_m','y_s_res'))
```

## Tab 5
```{r, echo=F, message=F, warning=F}
gcou$trplot(c('x','y','alpha'))
```

# Graphical: Rigged election process
## Tab 1
## Tab 2
## Tab 3	
## Tab 4

```{r}
combi <- combinat::combn(5, 3)
v <- seq(1,dim(combi)[2])
sdfc <- gcou$sdfc %>% dplyr::select(x,y,alpha,lambda,zeta,lambda)
v%>% purrr::map(function(x,comb=combi,df=sdfc){
		gdf <- df %>% dplyr::select(combi[,x])
		mrdfc <- as.matrix(gdf)
		x <- mrdfc[,1]
		y <- mrdfc[,2]
		z <- mrdfc[,3]
		plotly::plot_ly(x=x,y=y,z=z,type="scatter3d", mode="markers") %>%
	        plotly::layout(scene = list(xaxis = list(title = names(gdf)[1]),
                     yaxis = list(title = names(gdf)[2]),
                     zaxis = list(title = names(gdf)[3])))
}) -> og
og[1]
library(htmltools)
htmltools::browsable(div(
  style = "display: flex; flex-wrap: wrap; justify-content: center",
  div(og[1], style = "width: 40%; border: solid;"),
  div(og[2], style = "width: 40%; border: solid;"),
  div(og[3], style = "width: 40%; border: solid;"),
  div(og[4], style = "width: 40%; border: solid;"),
  div(og[5], style = "width: 40%; border: solid;"),
  div(og[6], style = "width: 40%; border: solid;"),
  div(og[7], style = "width: 40%; border: solid;"),
  div(og[8], style = "width: 40%; border: solid;"),
  div(og[9], style = "width: 40%; border: solid;"),
  div(og[10], style = "width: 40%; border: solid;")
))
```




























