#library(ManifoldDestiny)
abs_path <- paste0(rprojroot::find_rstudio_root_file())
lf <- list.files(paste0(abs_path,'/R/'))
for (t in 1:length(lf))source(paste0(abs_path,'/R/',lf[t]))
library(testthat)
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(randNames)
library(openxlsx)
library(patchwork)
library(writexl)
library(plotly)
library(ViewPipeSteps)
library(ggpubr)
library(htmltools)
vtest <- Voterdatabase()
vtest$realizedgp()
#View(vtest$listvbase[[1]])
#View(vtest$listvbase[[2]]%>%filter(C==1) %>% select(R,C))
#View(ctest$sdfc)
ctest <- Countingprocess(vtest$listvbase[[2]])
testthat::test_that("tautologies",{
  vf <- rowSums(ctest$sdfc[,c("a","b","c","d")])
  ve <- ctest$sdfc$V
  # 
  expect_equal(vf,ve) 
})

