---
title: "{{< var addnl >}}"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: false
---



```{r}
#| echo: false
#| output: false
#| message: false
#| warning: false
options(digits=2)
ManifoldDestiny::wasmconload()
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmconverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmnonverting.R"))
apps <- appn1
adat <- apps[[1]]
amet <- apps[[2]]
cogr <- Countinggraphs(apps[[1]])
selo <- seloutput(selreport(apps))
copl <- cogr$polyc[[1]][[1]]
```

### Without purge

::: {.panel-tabset}

### {{< var tabs.h1 >}}

```{r, echo=F}
kableExtra::kbl(selo[['decs']]) %>% kableExtra::kable_paper(full_width = F) %>% kableExtra::kable_styling(font_size=8)
```
### {{< var tabs.h2 >}}
```{r, echo=F, out.width="60%"}
selo[['corxy']]
```
### {{< var tabs.h3 >}}
```{r, echo=F, out.width="60%"}
selo[['qunt']]
```
### {{< var tabs.h4 >}}
```{r, echo=F}
selo[['ro3d']]
```
### {{< var tabs.h5 >}}
```{r, echo=F, out.width="60%"}
selo[['regr']]
```
### {{< var tabs.h6 >}}
```{r, echo=F, out.width="60%"}
selo[['cmp']]
```
### {{< var tabs.h7 >}}
```{r, echo=F, out.width="60%"}
selo[['resp']]
```
::: 










### With purge

```{r}
#| echo: false
#| output: false
#| message: false
#| warning: false
options(digits=2)
ManifoldDestiny::wasmconload()
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmconverting.R"))
source(paste0(rprojroot::find_rstudio_root_file(),"/R/wasmnonverting.R"))
appn1[[2]]$prg$cnd  <- 1
appn1[[2]]$prg$z  <- 200
apps <- appn1
adat <- apps[[1]]
amet <- apps[[2]]
cogr <- Countinggraphs(apps[[1]])
selo <- seloutput(selreport(apps))
selo[[2]]
copl <- cogr$polyc[[1]][[1]]
```



::: {.panel-tabset}

### {{< var tabs.h1 >}}

```{r, echo=F}
kableExtra::kbl(selo[['decs']]) %>% kableExtra::kable_paper(full_width = F) %>% kableExtra::kable_styling(font_size=8)
```
### {{< var tabs.h2 >}}
```{r, echo=F, out.width="60%"}
selo[['corxy']]
```
### {{< var tabs.h3 >}}
```{r, echo=F, out.width="60%"}
selo[['qunt']]
```
### {{< var tabs.h4 >}}
```{r, echo=F}
selo[['ro3d']]
```
### {{< var tabs.h5 >}}
```{r, echo=F, out.width="60%"}
selo[['regr']]
```
### {{< var tabs.h6 >}}
```{r, echo=F, out.width="60%"}
selo[['cmp']]
```
### {{< var tabs.h7 >}}
```{r, echo=F, out.width="60%"}
selo[['resp']]
```
::: 


[Independent spreadsheet calculations (Solomon)](https://docs.google.com/spreadsheets/d/1gkf41sJRAQ6bwKmlAAcb7hAQ6v4zIXG2wDYl67LrJ4k/edit?gid=59123130#gid=59123130)


```{r, echo=F}
knitr::knit_exit()
```


